apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "env.app_name" . }}-ingress-https
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | default "nginx" }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
    nginx.ingress.kubernetes.io/default-backend: {{ .Values.saas.template }}-error-page
spec:
  tls:
    - hosts:   
      - "{{ template "platform.host" . }}"
      secretName: {{ .Values.ingress.cert | default "wildcard-saas-tls" }}
  rules:
  - host: {{ template "platform.host" . }}
    http:
      paths:
      - backend:
          serviceName: "{{ template "env.app_name" . }}-{{ .Values.platform.service.name }}"
          servicePort: {{ .Values.platform.service.externalPort }}
        path: /