{{- if eq .Values.hpa.enabled true }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ template "env.app_name" . }}-prometheus-scaledobject"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod:  60
  pollingInterval: 10
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1  # Optional. Default: apps/v1
    kind: Rollout         # Optional. Default: Deployment
    name: {{ template "env.app_name" . }}-{{ .Values.platform.service.name }}                # Mandatory. Must be in the same namespace as the ScaledObject
    envSourceContainerName: saas-platform
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-k8s.monitoring.svc:9090
        metricName: nginx_ingress_controller_requests
        threshold: '100'
        query: sum(round(increase(nginx_ingress_controller_requests{ingress="{{ template "env.app_name" . }}-ingress-https"}[{{ .Values.hpa.keda.life_time }}])))
{{- end }}