apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "env.app_name" . }}-platform-secret-configmap"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  secret_custom: |
      {{ .Values.platform.vault.secrets }}
  config_init: |
      "auto_auth" = {
        "method" = {
          "config" = {
            "role" = "myapp"
          }
          "type" = "kubernetes"
        }

        "sink" = {
          "config" = {
            "path" = "/home/vault/.token"
          }

          "type" = "file"
        }
      }

      "exit_after_auth" = true
      "pid_file" = "/home/vault/.pid"

      "template" = {
        "source" = "/vault/configs/templates-base.hcl"
        "destination" = "/vault/secrets/config_base"
      }

        "template" = {
        "source" = "/vault/configs/templates-custom.hcl"
        "destination" = "/vault/secrets/config_custom"
      }

      "vault" = {
        "address" = {{ .Values.platform.vault.api_url | default "http://vault.hashicorp-vault.svc.cluster.local:8200" }}
      }