---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "env.app_name" . }}-platform-secret-configmap"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  secrets.hcl: |-
    {{- include "vault.secrets" . | nindent 4 }}
{{- range $secret, $template := .Values.platform.vault.secrets -}}
{{- printf "{{ with secret \"secret/%s\" }}" $secret | nindent 4 -}}
{{- printf "export %s" $template | nindent 4 -}}
{{- printf "{{ end }}" | nindent 4 -}}
{{- end -}}
  config-init.hcl: |-
    #commented
     "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "myapp"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "source" = "/vault/configs/secrets.hcl"
      "destination" = "/vault/secrets/config"
    }

    "vault" = {
      "address" = "{{ .Values.platform.vault.api_urls | default "http://hashicorp-vault.vault.svc.cluster.local:8200" }}"
    }