name: virtocommerce-saas-test
version: 0.0.1
apiVersion: v2
description: SaaS test solution
maintainers:  
    - name: Konstantin Kisilevskiy
      email: konstantin.kisilevsky@virtoway.com
appVersion: 1.0.0