kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "env.app_name" . }}-platform-cm"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  TAG: {{ .Values.platform.image.tag }}
  AppInsights__EnableDependencyTrackingTelemetryModule: "false"
  Swagger__UI__Enabled: "false"
  PushNotifications__ForceWebSockets: "true"
  PushNotifications__ScalabilityMode: "RedisBackplane"
  PushNotifications__HubUrl: "https://{{ template "platform.host" . }}/pushNotificationHub"
  PushNotifications__RedisBackplane__ChannelName: "{{ template "env.app_name" . }}-{{ .Release.Namespace }}-chanel"
  Search__ElasticSearch__Server: http://search-dev-es-http.elastic-system:9200
  Search__ElasticSearch__User: {{ template "env.app_name" . }}-{{ .Release.Namespace }}
  AzureAd__Enabled: "true"
  Search__Scope: "{{ template "env.app_name" . }}-platform{{ .Release.Namespace }}"
  Content__FileSystem__PublicUrl: "https://{{ template "platform.host" . }}/cms-content/"
  Assets__FileSystem__PublicUrl: "https://{{ template "platform.host" . }}/cms-content/assets/"
  Assets__FileSystem__RootPath: "~/cms-content/assets"
  Search__Provider: ElasticSearch
  VirtoCommerce__LicenseFilePath: app_data/VirtoCommerce.lic
  VirtoCommerce__LicensePublicKeyPath: app_data/public.key
  VirtoCommerce__LicensePrivateKeyPath: app_data/private.key
  VirtoCommerce__LocalUploadFolderPath: app_data/uploads
  VirtoCommerce__Hangfire__JobStorageType: SqlServer
  VirtoCommerce__RefreshProbingFolderOnStart: "false"
  VirtoCommerce__ProbingPath: "app_data/modules"
  Caching__CacheSlidingExpiration: "0:01:00"
  ExternalModules__ModulesManifestUrl: ""
  ExternalModules__AutoInstallModuleBundles: |
    [
      "none"
    ]
{{- range $key, $value := .Values.platform.config }}
  {{ $key | nindent 2 }}: {{ $value | quote }}
{{- end }}
