{{- if and (eq .Values.hpa.enabled true) (eq .Values.saas.template "production") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ template "env.app_name" . }}-cpu-scaledobject"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  minReplicaCount: 2
  maxReplicaCount: 4
  cooldownPeriod:  60
  pollingInterval: 10
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1  # Optional. Default: apps/v1
    kind: Rollout         # Optional. Default: Deployment
    name: {{ template "env.app_name" . }}-{{ .Values.platform.service.name }}                # Mandatory. Must be in the same namespace as the ScaledObject
    envSourceContainerName: saas-platform
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
{{- end }}