apiVersion: v1
kind: Service
metadata:
  name: "{{ template "env.app_name" . }}-{{ .Values.platform.service.name }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.platform.service.externalPort }}
  selector:
    "{{ template "env.app_name" . }}-platform"