kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "env.app_name" . }}-storefront-cm"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: Development
  VirtoCommerce__Endpoint__Password: store
  VirtoCommerce__Endpoint__UserName: admin
  VirtoCommerce__Endpoint__Url: "http://{{ template "env.app_name" . }}-{{ .Values.platform.service.name }}.saas.svc.cluster.local"