apiVersion: v1
kind: Service
metadata:
  name: "{{ template "env.app_name" . }}-{{ .Values.storefront.service.name }}"
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.storefront.service.externalPort }}
  selector:
    {{- include "app.storefrontLabels" . | nindent 4 }}